//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSP_DEVEntities : DbContext
    {
        public TSP_DEVEntities()
            : base("name=TSP_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCat_Modulo> tblCat_Modulo { get; set; }
        public virtual DbSet<tblCat_DetalleProceso> tblCat_DetalleProceso { get; set; }
        public virtual DbSet<tblCat_WBS> tblCat_WBS { get; set; }
        public virtual DbSet<tblCat_Equipo> tblCat_Equipo { get; set; }
        public virtual DbSet<tblCat_Usuarios> tblCat_Usuarios { get; set; }
        public virtual DbSet<tblRel_Equipos> tblRel_Equipos { get; set; }
        public virtual DbSet<tblRel_ProcesoRevision> tblRel_ProcesoRevision { get; set; }
        public virtual DbSet<tblRel_EquipoFecha> tblRel_EquipoFecha { get; set; }
        public virtual DbSet<tblCat_Plan> tblCat_Plan { get; set; }
        public virtual DbSet<tblCat_TipoTarea> tblCat_TipoTarea { get; set; }
        public virtual DbSet<tblCat_Sistema> tblCat_Sistema { get; set; }
        public virtual DbSet<tblCat_Proceso> tblCat_Proceso { get; set; }
        public virtual DbSet<tblCat_VersionProceso> tblCat_VersionProceso { get; set; }
        public virtual DbSet<tblRel_EquipoPlan> tblRel_EquipoPlan { get; set; }
        public virtual DbSet<tblCat_Perfil> tblCat_Perfil { get; set; }
        public virtual DbSet<tblRel_UsuarioPerfil> tblRel_UsuarioPerfil { get; set; }
        public virtual DbSet<tblCat_ControlesUI> tblCat_ControlesUI { get; set; }
        public virtual DbSet<tblCat_TareasOpcionales> tblCat_TareasOpcionales { get; set; }
    }
}
