//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_WBS
    {
        public int iIdWBS { get; set; }
        public int iIdPlan { get; set; }
        public int iRequerimiento { get; set; }
        public int iIdProcesos { get; set; }
        public int iIdDetalleProceso { get; set; }
        public decimal cWork_Item_Type { get; set; }
        public int iTipoElemento { get; set; }
        public decimal dRemaining_Work { get; set; }
        public decimal dOriginal_Estimate { get; set; }
        public decimal dTiempo_Total_del_proceso { get; set; }
        public decimal dPorcentaje_de_tareas { get; set; }
        public decimal dtamanios { get; set; }
        public decimal dRate { get; set; }
        public decimal dValor_ganado { get; set; }
        public int isemana { get; set; }
        public decimal dValor_ganado_acumulado { get; set; }
        public decimal dValor_ganado_semanal { get; set; }
        public int iIdTipoTarea { get; set; }
        public string cUnidad_de_medida { get; set; }
        public System.DateTime dtFecha_de_inicio { get; set; }
        public System.DateTime dtFechaFinal { get; set; }
        public System.DateTime dtHoras_Acumuladas { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
        public bool lActivo { get; set; }
        public Nullable<int> iIdTFS { get; set; }
        public System.Guid iIdUsuario { get; set; }
        public int iGrupo { get; set; }
        public bool lAplicaMultiProceso { get; set; }
        public string cTituloProceso { get; set; }
        public Nullable<int> iRevision { get; set; }
        public Nullable<System.DateTime> dtTimeStamp { get; set; }
        public int iOrdenDetalleProceso { get; set; }
        public int iOrdenProceso { get; set; }
        public Nullable<int> iOrdenRequerimiento { get; set; }
        public Nullable<int> iOrden { get; set; }
    
        public virtual tblCat_DetalleProceso tblCat_DetalleProceso { get; set; }
        public virtual tblCat_Plan tblCat_Plan { get; set; }
        public virtual tblCat_Proceso tblCat_Proceso { get; set; }
        public virtual tblCat_Usuarios tblCat_Usuarios { get; set; }
        public virtual tblCat_TipoTarea tblCat_TipoTarea { get; set; }
    }
}
