//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_ControlesUI
    {
        public int iIdControlesUI { get; set; }
        public string cIdHTML { get; set; }
        public bool lHabilitado { get; set; }
        public int iIdPerfil { get; set; }
    
        public virtual tblCat_Perfil tblCat_Perfil { get; set; }
    }
}
