//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_Equipo()
        {
            this.tblRel_Equipos = new HashSet<tblRel_Equipos>();
            this.tblRel_ProcesoRevision = new HashSet<tblRel_ProcesoRevision>();
            this.tblRel_EquipoFecha = new HashSet<tblRel_EquipoFecha>();
            this.tblRel_EquipoPlan = new HashSet<tblRel_EquipoPlan>();
        }
    
        public int iIdEquipo { get; set; }
        public string cNombreEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRel_Equipos> tblRel_Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRel_ProcesoRevision> tblRel_ProcesoRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRel_EquipoFecha> tblRel_EquipoFecha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRel_EquipoPlan> tblRel_EquipoPlan { get; set; }
    }
}
