//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_Proceso()
        {
            this.tblCat_DetalleProceso = new HashSet<tblCat_DetalleProceso>();
            this.tblRel_ProcesoRevision = new HashSet<tblRel_ProcesoRevision>();
            this.tblCat_WBS = new HashSet<tblCat_WBS>();
            this.tblCat_VersionProceso = new HashSet<tblCat_VersionProceso>();
        }
    
        public int iIdProceso { get; set; }
        public string cNombreProceso { get; set; }
        public string cDescripcion { get; set; }
        public int iOrden { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
        public bool lActivo { get; set; }
        public Nullable<bool> lEditable { get; set; }
        public int iTipoProceso { get; set; }
        public bool lVisualizarCombo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_DetalleProceso> tblCat_DetalleProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRel_ProcesoRevision> tblRel_ProcesoRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_WBS> tblCat_WBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_VersionProceso> tblCat_VersionProceso { get; set; }
    }
}
