//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Modulo
    {
        public int iIdModulo { get; set; }
        public string cNombreModulo { get; set; }
        public string cDescripcion { get; set; }
        public string cRuta { get; set; }
        public int iOrden { get; set; }
        public int iImagen { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
        public bool lActivo { get; set; }
        public int iIdSistema { get; set; }
        public int iIdClasePermiso { get; set; }
        public int lGrid { get; set; }
        public bool lFrontEnd { get; set; }
    
        public virtual tblCat_Sistema tblCat_Sistema { get; set; }
    }
}
