//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_DetalleProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_DetalleProceso()
        {
            this.tblCat_WBS = new HashSet<tblCat_WBS>();
        }
    
        public int iIdDetalleProceso { get; set; }
        public string cNombreDetalleProceso { get; set; }
        public System.DateTime dtAlta { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
        public Nullable<int> iIdProceso { get; set; }
        public bool lActivo { get; set; }
        public Nullable<int> iIdTipoTarea { get; set; }
        public Nullable<int> iRevision { get; set; }
        public int iIdVersionProceso { get; set; }
        public bool lRequerida { get; set; }
        public decimal dPorcentaje { get; set; }
        public bool lTamaño { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_WBS> tblCat_WBS { get; set; }
        public virtual tblCat_Proceso tblCat_Proceso { get; set; }
        public virtual tblCat_VersionProceso tblCat_VersionProceso { get; set; }
    }
}
